import { TerminalModel } from './model';
import { ITerminalOptions, ITheme, Terminal as XTerminal } from '@xterm/xterm';
import { Pty } from './pty';
export declare class TerminalElement extends HTMLElement {
    #private;
    model?: TerminalModel;
    terminal?: XTerminal;
    pty?: Pty;
    initialized: boolean;
    private subscriptions;
    private initializedPromise?;
    private findPalette?;
    private div?;
    static create(): TerminalElement;
    initialize(model: TerminalModel): Promise<void>;
    ready(): Promise<void | undefined>;
    getModel(): TerminalModel | undefined;
    destroy(): void;
    getShellCommand(): any;
    getArgs(): any[];
    getTerminalType(): any;
    pathIsDirectory(filePath: string | undefined | null): Promise<boolean>;
    getCwd(): Promise<string | undefined>;
    getEnv(): Record<string, string>;
    getEncoding(): any;
    leaveOpenAfterExit(): any;
    isPtyProcessRunning(): boolean | undefined;
    getExtraXTermOptions(): Partial<ITerminalOptions>;
    getXtermOptions(): ITerminalOptions;
    setMainBackgroundColor(theme?: ITheme): void;
    optionallyWarnAboutModifierlessClick(): void;
    createTerminal(): Promise<void>;
    updateTheme(): void;
    showFind(prefilledText?: string): boolean;
    toggleFind(): boolean;
    hideFind(): boolean;
    findNext(): boolean;
    findPrevious(): boolean;
    showNotification(message: string, infoType: string, { restartButtonText, force }?: {
        restartButtonText?: string;
        force?: boolean;
    }): void;
    promptToStartup(): Promise<void>;
    restartPtyProcess(): Promise<void>;
    clear(): void;
    sendSequence(sequence: string[]): boolean;
    refitTerminal(): void;
    focusTerminal(double?: boolean): Promise<void>;
    selectAll(): void;
    hide(): void;
    show(): void;
}
